### PR TITLE
Updated dependencies so that travis will pass

### PR DESCRIPTION
**Pull request by ghost**
`npm run test` passed for me, and my monochrome image optimized without error (tested it manually too).

### CODE REVIEW

**Comment by gagern** [comment]
According to [npm semver docs](https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004), the changes to `jshint` and `buffer-crc32` should not be neccessary as the caret ranges already cover the version you're changing to. For the others, we have potentially breaking changes, and I'd look at the documentation for these changes to see in what way they broke backwards compatibility. If you want to help there, research some links to where these changes are documented.

**Comment by gagern** [comment]
* https://github.com/nodeca/pako/blob/master/CHANGELOG.md lists no relevant changes. Not sure why they did bump major version at all.
* https://github.com/mochajs/mocha/blob/master/CHANGELOG.md indicates incompatibility with really old versions of node and npm. I'm fine with that.
* `should` doesn't seem to have a change log. We can only hope it works as it should, pardon the pun.
* `vendor-icons` is tricky. I wanted this as a fixed version, so I could [rely on a spcific icon for my tests](https://github.com/gagern/jspngopt/blob/master/test/Optimizer.js#L11). But apparently this is the very package causing problems on Travis, as that version isn't available from npm any more. Not sure why, perhaps some legal reason. I guess that instead of bumping the dependency here, I'll just add some sample image to my repository.

**Comment by ghost** [comment]
Okay, I saw you had tests and I didn't analyze your tests too much. I figured if your basic tests pass it would be okay. I tested it for my needs (my monochrome image from `pngquant 2 foo.png`). I don't have time to get more involved in this at the moment.

Thanks for checking out the deps :+1:

**Comment by gagern** [comment]
No problem. Thanks for the interest, for making me aware of the failing test (which I hadn't noticed as I do have the dependency installed locally) and for suggesting a patch. I will take it from here, and should have a new release before Christmas.

**Comment by gagern** [comment]
Superseded by 8e54b5d5b51c45b061e678010727a0b6cfd1761a.

**Pull request closed without merging**
